[federation]
domain = "localhost"
allowed_origins = ["http://localhost:8081"]

[database]
connection_url = "postgres://ibis:ibis@db:5432/ibis"

[setup]
admin_username = "admin"
admin_password = "admin123"

[server]
cors_allowed_origins = ["http://localhost:8081"]
