services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ibis
      POSTGRES_PASSWORD: ibis
      POSTGRES_DB: ibis
    volumes:
      - ibis-data:/var/lib/postgresql/data
    networks:
      - ibis-net

  ibis:
    build: .
    environment:
      LEPTOS_SITE_ADDR: "0.0.0.0:3000"
      DATABASE_URL: "postgres://ibis:ibis@db:5432/ibis"
    depends_on:
      - db
    ports:
      - "8081:8081"
      - "3000:3000"
    networks:
      - ibis-net
    volumes:
      - ./config.toml:/app/config.toml

volumes:
  ibis-data:

networks:
  ibis-net:
