version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ibis
      POSTGRES_PASSWORD: ibis
      POSTGRES_DB: ibis
    volumes:
      - ibis-data:/var/lib/postgresql/data
    networks:
      - ibis-net

  ibis:
    build: .
    environment:
      LEPTOS_SITE_ADDR: "0.0.0.0:8081"
      DATABASE_URL: "postgres://ibis:ibis@db:5432/ibis"
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - ibis-net

volumes:
  ibis-data:

networks:
  ibis-net:
